#! /bin/sh

### BEGIN INIT INFO
# Provides:          Autonomy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run RPi Zero Autonomous Robot
### END INIT INFO

# If you want a command to always run, put it here
# to register:   sudo update-rc.d NameOfYourScript defaults
# to deregister: sudo update-rc.d -f  NameOfYourScript remove
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Autonomy"
    # run application you want to start
    cd /home/pi
    python autonomy.py &
    ;;
  stop)
    echo "Stopping Autonomy"
    # kill application you want to stop
    pkill -f autonomy.py
    ;;
  *)
    echo "Usage: /etc/init.d/autonomy {start|stop}"
    exit 1
    ;;
esac

exit 0
